# Generated by Django 6.0.3 on 2026-03-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/'),
        ),
    ]
